version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: ./env/php/Dockerfile
    container_name: bgg_app
    restart: always
    tty: true
    links:
      - db
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www/
      - ./env/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: bgg_webserver
    restart: always
    tty: true
    ports:
      - "8181:80"
      - "8282:443"
    volumes:
      - ./src:/var/www
      - ./env/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: bgg_db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker_laravel
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  npm:
    image: node:10
    container_name: bgg_npm
    restart: always
    working_dir: /var/www/
    entrypoint: ["npm"]
    volumes:
      - "./src/:/var/www/"

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local